- name: demo on printing the variable on play level
  hosts: all
  vars:
    first_name: pavan # defining the variable at playlevel
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: name on play level {{first_name}} #printing the variable value first_name here


- name: demo on variable on task level
  hosts: all
  tasks:
    - name: print the task level variable
      ansible.builtin.debug:
        msg: name on task level {{last_name}}  # calling the task level variable
      vars:         # variable at task level
        last_name: bairu    #only this task is able to access the variable and other tasks cannot access


# variable files on play bool level
- name: demo on print from var_files
  hosts: all
  vars_files:  # variable files
    - ex-vars.yml   #file name
  tasks:
    - name: print the variable from ex-vars.yml file
      ansible.builtin.debug:
        msg: middle name from file {{middle_name}}