# the variable at playlevel
- name: demo on printing the variable on play level
  hosts: all
  vars:
    first_name: pavan                           # defining the variable at playlevel
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: name on play level {{first_name}}  #printing the variable value first_name here


# the variable at tasklevel
- name: demo on variable on task level
  hosts: all
  tasks:
    - name: print the task level variable
      ansible.builtin.debug:
        msg: name on task level {{last_name}}   # calling the task level variable
      vars:                                     # variable at task level
        last_name: bairu                  # only this task is able to access the variable and other tasks cannot access


# variable files on play bool level
#it does not support on task level. only on play level
- name: demo on print from var_files
  hosts: all
  vars_files:                                          # variable files
    - ex-vars.yml                                      # file name
  tasks:
    - name: print the variable from ex-vars.yml file
      ansible.builtin.debug:
        msg: middle name from file {{middle_name}}


# variable from roles/sample(role_name)/vars
- name: demo on variable from roles/sample(role_name)/vars
  hosts: all
  vars:
    address: warangal    # this variable can be accessed for all the roles
  roles:
    - sample(role_name)  # this varibale can not be accessed for all the roles only accessed for sample(role_name) role


# register variables using shell module
- name: demo on register variables
  hosts: all
  tasks:
    - name: register variables shell module
      ansible.builtin.shell: uptime           # calculate the time for running the playbook
      register: output                        # stores the uptime value in output variable

    - name: print the output
      ansible.builtin.debug:
        msg: '{{output}}'                       # printing the uptime value

