- name: print the parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: print the parameter value
      ansible.builtin.debug:
        msg: parameter -> {{ lookup('aws_ssm', 'test', region='us-east-1' ) }}